//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace Orleans.StorageProvider.Blob.Test.GrainInterfaces
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using Orleans.Runtime;
    using System.Collections;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class Grain1Factory
    {
        

                        public static Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1 GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1), -2036359571, primaryKey));
                        }

                        public static Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1 GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1), -2036359571, primaryKey, grainClassNamePrefix));
                        }

                        public static Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1 GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1), -2036359571, primaryKey));
                        }

                        public static Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1 GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1), -2036359571, primaryKey, grainClassNamePrefix));
                        }

            public static Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1 Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return Grain1Reference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Orleans.StorageProvider.Blob.Test.GrainInterfaces.Orleans.StorageProvider.Blob.Te" +
            "st.GrainInterfaces.IGrain1")]
        internal class Grain1Reference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1
        {
            

            public static Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1 Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1), (global::Orleans.Runtime.GrainReference gr) => { return new Grain1Reference(gr);}, grainRef, -2036359571);
            }
            
            protected internal Grain1Reference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal Grain1Reference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return -2036359571;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Orleans.StorageProvider.Blob.Test.GrainInterfaces.Orleans.StorageProvider.Blob.Te" +
                        "st.GrainInterfaces.IGrain1";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                Grain1Reference input = ((Grain1Reference)(original));
                return ((Grain1Reference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                Grain1Reference input = ((Grain1Reference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return Grain1Reference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return Grain1MethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1.Set(string stringValue, int intValue, System.DateTime dateTimeValue, System.Guid guidValue, Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1 grainValue)
            {

                return base.InvokeMethodAsync<object>(-394250501, new object[] {stringValue, intValue, dateTimeValue, guidValue, grainValue is global::Orleans.Grain ? Orleans.StorageProvider.Blob.Test.GrainInterfaces.Grain1Factory.Cast(grainValue.AsReference()) : grainValue} );
            }
            
            System.Threading.Tasks.Task<System.Tuple<string, int, System.DateTime, System.Guid, Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1>> Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1.Get()
            {

                return base.InvokeMethodAsync<System.Tuple<System.String,System.Int32,System.DateTime,System.Guid,Orleans.StorageProvider.Blob.Test.GrainInterfaces.IGrain1>>(-940922787, new object[] {} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Orleans.StorageProvider.Blob.Test.GrainInterfaces.Orleans.StorageProvider.Blob.Te" +
        "st.GrainInterfaces.IGrain1", -2036359571)]
    internal class Grain1MethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return -2036359571;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -2036359571:  // IGrain1
                        switch (methodId)
                        {
                            case -394250501: 
                                return ((IGrain1)grain).Set((String)arguments[0], (Int32)arguments[1], (DateTime)arguments[2], (Guid)arguments[3], (IGrain1)arguments[4]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -940922787: 
                                return ((IGrain1)grain).Get().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -2036359571:  // IGrain1
                    switch (methodId)
                    {
                        case -394250501:
                            return "Set";
                    case -940922787:
                            return "Get";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
